services:

  api:
    image: 803018310241.dkr.ecr.eu-central-1.amazonaws.com/edim-api:latest
    container_name: edim-api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
      - redis
    command: >
      bash -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  telegram-bot:
    image: 803018310241.dkr.ecr.eu-central-1.amazonaws.com/edim-telegram:latest
    container_name: edim-telegram
    restart: always
    env_file:
      - .env
    depends_on:
      - api

  postgres:
    image: postgres:15
    container_name: edim-postgres
    restart: always
    environment:
      POSTGRES_DB: copilot
      POSTGRES_USER: copilot
      POSTGRES_PASSWORD: copilot
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: edim-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: edim-redis
    restart: always

volumes:
  postgres_data:
  mongo_data: