"""added unit debt

Revision ID: 588465b7ab7d
Revises: 71774f5d3c4f
Create Date: 2026-02-23 11:01:58.357632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588465b7ab7d'
down_revision: Union[str, Sequence[str], None] = '71774f5d3c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('debt_total', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'debt_total')
    # ### end Alembic commands ###
