"""extended provider

Revision ID: 6dea0b6f203a
Revises: cf84e378be7e
Create Date: 2026-02-21 12:37:39.096841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dea0b6f203a'
down_revision: Union[str, Sequence[str], None] = 'cf84e378be7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('integration_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('providers', sa.Column('last_import_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'last_import_at')
    op.drop_column('providers', 'integration_config')
    # ### end Alembic commands ###
