"""added user-organization relation

Revision ID: 71774f5d3c4f
Revises: ba6f24e097db
Create Date: 2026-02-22 19:20:49.105382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71774f5d3c4f'
down_revision: Union[str, Sequence[str], None] = 'ba6f24e097db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('address', sa.String(), nullable=True))
    op.create_index(op.f('ix_buildings_address'), 'buildings', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buildings_address'), table_name='buildings')
    op.drop_column('buildings', 'address')
    # ### end Alembic commands ###
