"""add provider

Revision ID: 9db7ade56db3
Revises: da1890dcb53a
Create Date: 2026-02-21 07:18:26.026933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db7ade56db3'
down_revision: Union[str, Sequence[str], None] = 'da1890dcb53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_provider_id'), 'organizations', ['provider_id'], unique=False)
    op.add_column('buildings', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_buildings_organization_id'), 'buildings', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'buildings', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.drop_index(op.f('ix_buildings_organization_id'), table_name='buildings')
    op.drop_column('buildings', 'organization_id')
    op.drop_index(op.f('ix_organizations_provider_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('providers')
    # ### end Alembic commands ###
