"""user phone

Revision ID: a0192808753d
Revises: 49b43fe34279
Create Date: 2026-02-20 11:48:50.588521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0192808753d'
down_revision: Union[str, Sequence[str], None] = '49b43fe34279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_apartment_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'apartment_id')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('apartment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_apartment_id_fkey'), 'users', 'apartments', ['apartment_id'], ['id'])
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
