"""rename apartment to unit

Revision ID: b4519dd6397f
Revises: 54655c444313
Create Date: 2026-02-21 08:54:04.611511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4519dd6397f'
down_revision: Union[str, Sequence[str], None] = '54655c444313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'number', 'unit_type', name='uq_unit_building_number_type')
    )
    op.create_index(op.f('ix_units_building_id'), 'units', ['building_id'], unique=False)
    op.create_table('user_units',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('since', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'unit_id')
    )
    op.create_index('idx_user_unit_unit', 'user_units', ['unit_id'], unique=False)
    op.create_index('idx_user_unit_user', 'user_units', ['user_id'], unique=False)
    op.drop_index(op.f('idx_user_apartment_apartment'), table_name='user_apartments')
    op.drop_index(op.f('idx_user_apartment_user'), table_name='user_apartments')
    op.drop_table('user_apartments')
    op.drop_index(op.f('ix_apartments_building_id'), table_name='apartments')
    op.drop_table('apartments')
    op.drop_column('providers', 'integration_config')
    op.drop_column('providers', 'last_import_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('last_import_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('providers', sa.Column('integration_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('apartments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('building_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('apartments_building_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('apartments_pkey')),
    sa.UniqueConstraint('building_id', 'number', name=op.f('uq_apartment_building_number'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_apartments_building_id'), 'apartments', ['building_id'], unique=False)
    op.create_table('user_apartments',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('apartment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('since', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name=op.f('user_apartments_apartment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_apartments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'apartment_id', name=op.f('user_apartments_pkey'))
    )
    op.create_index(op.f('idx_user_apartment_user'), 'user_apartments', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_apartment_apartment'), 'user_apartments', ['apartment_id'], unique=False)
    op.drop_index('idx_user_unit_user', table_name='user_units')
    op.drop_index('idx_user_unit_unit', table_name='user_units')
    op.drop_table('user_units')
    op.drop_index(op.f('ix_units_building_id'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
