"""extended unit

Revision ID: ba00801dd16e
Revises: 6dea0b6f203a
Create Date: 2026-02-21 14:00:53.352738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba00801dd16e'
down_revision: Union[str, Sequence[str], None] = '6dea0b6f203a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('section', sa.String(), nullable=True))
    op.add_column('units', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('area_total', sa.Float(), nullable=True))
    op.add_column('units', sa.Column('rooms', sa.Integer(), nullable=True))
    op.add_column('units', sa.Column('personal_account', sa.String(), nullable=True))
    op.create_index(op.f('ix_units_personal_account'), 'units', ['personal_account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_personal_account'), table_name='units')
    op.drop_column('units', 'personal_account')
    op.drop_column('units', 'rooms')
    op.drop_column('units', 'area_total')
    op.drop_column('units', 'floor')
    op.drop_column('units', 'section')
    # ### end Alembic commands ###
