"""user apartment m2m

Revision ID: da1890dcb53a
Revises: 0e7390b8336b
Create Date: 2026-02-20 15:22:40.658834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1890dcb53a'
down_revision: Union[str, Sequence[str], None] = '0e7390b8336b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_apartments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('since', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'apartment_id')
    )
    op.create_index('idx_user_apartment_apartment', 'user_apartments', ['apartment_id'], unique=False)
    op.create_index('idx_user_apartment_user', 'user_apartments', ['user_id'], unique=False)
    op.add_column('apartments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_apartments_building_id'), 'apartments', ['building_id'], unique=False)
    op.create_unique_constraint('uq_apartment_building_number', 'apartments', ['building_id', 'number'])
    op.drop_constraint(op.f('apartments_building_id_fkey'), 'apartments', type_='foreignkey')
    op.create_foreign_key(None, 'apartments', 'buildings', ['building_id'], ['id'], ondelete='CASCADE')
    op.add_column('buildings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chat_identities', sa.Column('phone', sa.String(), nullable=True))
    op.add_column(
        "chat_identities",
        sa.Column("verified", sa.Boolean(), nullable=True),
    )
    op.execute(
        "UPDATE chat_identities SET verified = false WHERE verified IS NULL"
    )
    op.alter_column(
        "chat_identities",
        "verified",
        nullable=False,
    )
    op.drop_index(op.f('ix_chat_identities_external_id'), table_name='chat_identities')
    op.create_index('idx_chat_identity_user', 'chat_identities', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_identities_channel'), 'chat_identities', ['channel'], unique=False)
    op.create_index(op.f('ix_chat_identities_user_id'), 'chat_identities', ['user_id'], unique=False)
    op.create_unique_constraint('uq_chat_identity_channel_external', 'chat_identities', ['channel', 'external_id'])
    op.drop_constraint(op.f('chat_identities_user_id_fkey'), 'chat_identities', type_='foreignkey')
    op.create_foreign_key(None, 'chat_identities', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_constraint(None, 'chat_identities', type_='foreignkey')
    op.create_foreign_key(op.f('chat_identities_user_id_fkey'), 'chat_identities', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_chat_identity_channel_external', 'chat_identities', type_='unique')
    op.drop_index(op.f('ix_chat_identities_user_id'), table_name='chat_identities')
    op.drop_index(op.f('ix_chat_identities_channel'), table_name='chat_identities')
    op.drop_index('idx_chat_identity_user', table_name='chat_identities')
    op.create_index(op.f('ix_chat_identities_external_id'), 'chat_identities', ['external_id'], unique=False)
    op.drop_column('chat_identities', 'verified')
    op.drop_column('chat_identities', 'phone')
    op.drop_column('buildings', 'created_at')
    op.drop_constraint(None, 'apartments', type_='foreignkey')
    op.create_foreign_key(op.f('apartments_building_id_fkey'), 'apartments', 'buildings', ['building_id'], ['id'])
    op.drop_constraint('uq_apartment_building_number', 'apartments', type_='unique')
    op.drop_index(op.f('ix_apartments_building_id'), table_name='apartments')
    op.drop_column('apartments', 'created_at')
    op.drop_index('idx_user_apartment_user', table_name='user_apartments')
    op.drop_index('idx_user_apartment_apartment', table_name='user_apartments')
    op.drop_table('user_apartments')
    # ### end Alembic commands ###
